name: Commit

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  run_unit_tests:
    runs-on: ubuntu-latest
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup environment for developing
        run: sudo apt install -y golang make postgresql

      - name: Validate postgreqsql server has started
        run: |
          sleep 10
          pg_isready -U "postgres" -h 127.0.0.1 -p 5432

      - name: Run unit test suites
        run: make test

