name: Commit

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  run_unit_tests:
    runs-on: ubuntu-latest
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup environment for developing
        run: sudo apt install -y golang make postgres

      - name: Run unit test suites
        run: make test

